folder_to_process: "../examples/sdpt" #"./test_folder/"
summary_csv: "summary_TD.csv"

# File filtering & outputs
file_extension: ".cha"
detailed: true
details_path: "_details.csv"
details_folder: "../examples/output" #"./output_details/"

# Selection logic (formerly "is_plus", now "filtered")
conditions:
  filtered:
    any:
      - include: '(?i)\[\s*\+\s*rr\s*\]\s*\[\s*\+\s*ads\s*\]\s*\[\s*\+\s*\d+\s*\]\s*$'